site_name: Video Conferencing with Zoom Documentation
repo_url: https://github.com/techies23/video-conference-zoom
site_author: Deepen Bajracharya
copyright: Deepen Bajracharya
nav:
  - Getting Started: index.md
  - Installation:
      - Setup: setup.md
      - Migration from JWT: migration.md
  - Usage:
#      - Meeting Types: meeting_types.md
      - Webinars: webinars.md
      - Blocks: blocks.md
      - Shortcode: shortcode.md
      - Join via Browser: join_links.md
      - PRO Version Shortcode: pro-shortcode.md
      - Change DateTime: date_types.md
      - Vanity URL: vanity_url.md
      - Template Override: template_override.md
      - Filter Hooks: filters_hooks.md
      - Import Meeting: import-meetings.md
      - Host to WP: assign_host.md
      - WebHooks: webhooks.md
  - Addons:
      - Video Conferencing with Zoom Pro: vczapi-pro.md
      - WooCommerce (Addon): woocommerce.md
      - WooCommerce Product Vendors (Addon): woocommerce-product-vendors.md
      - WooCommerce Bookings (Addon): woocommerce-booking.md
      - Booked Appointments (Addon): booked-appointments.md
      - Dokan Integration for Zoom (Addon): dokan.md
      - WCFM (Addon): wcfm.md
      - WooCommerce Appointments (addon): woocommerce-appointments.md
  - FAQ: faq.md
  - Support: support.md
theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
  font:
    text: Rubik

